### ISSUE TITLE
getting io is not defined

### ISSUE THREAD

**Issue by zoharsherman** [joeherold/angular2-sails#8]
ReferenceError: io is not defined
    at Object.<anonymous> (http://localhost:8100/build/main.js:56191:5)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:100897:77)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:89023:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:126107:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

**Comment by joeherold** [comment]
did you implement io in your project?

**Comment by joeherold** [comment]
yes.
you have to add socket.io to your project. e.g. add your sails.io.js
(SAILS_ROOT/assets/js/depenencies/sails.io.js)
in angular2-sails, io is just declared, but you need to add it yourself

**Comment by joeherold** [comment]
or add sails.io.js to the scripts array of your webpack config

**Comment by zoharsherman** [comment]
i am using an ionic2 app (cordova) not a sails app
so i was able to get it working by adding:
(APP_ROOT/src/assets/depenencies/sails.io.js)
and adding to index.html (just after the  body tag)
<script src="assets/depenencies/sails.io.js"></script>

is there a better way to include the io? i tried adding npm install --save sails.io.js-dist
but it didn't work

**Comment by joeherold** [comment]
is ionic2 with system.js or webpack?

**Comment by joeherold** [comment]
that's, what I have found for ionic 2 with jQuery. Should work exact the same way with io.js (sails.io.js):
[Using an existing js library (jQuery) in ionic 2](https://forum.ionicframework.com/t/using-an-existing-js-library-jquery-in-ionic-2/52039)

**Comment by joeherold** [comment]
no more complaints so far, I will close.. :)
